### ISSUE TITLE
The specification?

### ISSUE THREAD

**Issue by bortzmeyer** [AntoineGagne/robots#9]
The beginning of  `src/robots.erl` says "Parse and manipulate robots.txt files according to the specification". Which specification? There are at least two, [the original one](http://www.robotstxt.org/orig.html) and the [RFC 9309](https://www.rfc-editor.org/info/rfc9309), more complex. (For instance, the original specification had no wildcards and no Allow.) I assume you follow the RFC?

**Comment by AntoineGagne** [comment]
You are correct, it follows the RFC

**Comment by bortzmeyer** [comment]
If it is supposed to follow the RFC, I suggest to write it in the doc.
